spring.application.name=hospitalManagement

server.servlet.context-path=/api/v1

# Database Connection Settings
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/hospitalDBDemo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#security config
#spring.security.user.name=anjali
#spring.security.user.password=pass
jwt.secretKey=${JWT_SECRET_KEY:dev-only-change-me-dev-only-change-me-dev-only-change-me-dev-only-change-me}


# Spring AI Configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.2


# Enable Spring AI pgvector store
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536
